FIX: add skip tag for utils
carpentries-incubator/SDC-BIDS-dMRI pull request #139
Opened 2021-04-17 15:25 UTC by kaitj

Adds the `#nbval_skip` tag to the cell causing failure for the workflow in the deterministic notebook. Also take advantage of commit to remove a local path from one of the cells.

2021-04-17 15:48 UTC, jhlegarreta submitted a review, later dismissed

2021-04-17 23:16 UTC, jhlegarreta requested changes
@kaitj I'm thinking that instead of skipping the whole solution cell, it might be better to split the solution into cells that do the necessary computations from the one that does the visualization part. Otherwise the solution does not get tested. Thanks.

2021-04-18 02:47 UTC, kaitj commented
Split the visualizations in the solutions notebook in de36551. Also used the commit to add the skip tag for exercise 2.

2021-04-19 13:55 UTC, jhlegarreta approved these changes
Warnings will need to be addressed at some point.

2021-04-21 12:59 UTC, merged