Update introduction to diffusion MRI lesson
carpentries-incubator/SDC-BIDS-dMRI pull request #222
Opened 2023-04-06 12:45 UTC by Bradley-Karat

Added in and expanded upon the current information in the introduction to diffusion MRI lesson. This includes changes to improve clarity and the logical flow of the lesson. Also changed the first figure to something that is a bit more clear (i.e. easier to understand the signal change via gradient direction change).

2023-04-10 16:52 UTC, kaitj reviewed
Content-wise, this seems good to me. 
Should run this through a linter for formatting / consistency with other lessons

2023-04-12 00:17 UTC, jhlegarreta reviewed
A few in-line comments.

The old image should be removed from the repository if it is no longer used.

Do not forget to apply them to the Jupyter Notebook.

Also, please squash all commits into a single one in this case.

2023-04-12 00:17 UTC, jhlegarreta commented on _episodes/introduction.md
> +diffusion-weighted images (DWI). Water diffusion that is occuring along the same
occuring -> occurring

2023-04-12 00:17 UTC, jhlegarreta commented on _episodes/introduction.md
> +Diffusion along X, Y, and Z directions. The signal in the left-right oriented corpus callosum
left-right oriented -> left-right-oriented or left/right oriented (?)

2023-04-12 00:17 UTC, jhlegarreta commented on _episodes/introduction.md
> +is lowest when measured along X, while the signal in the inferior-superior oriented corticospinal
inferior-superior oriented -> inferior-superior-oriented or inferior/superior oriented (?)

2023-04-12 00:17 UTC, jhlegarreta commented on _episodes/introduction.md
> +timing & strength of the diffusion gradients. A larger b-value means our DWI signal
& -> and

2023-04-12 00:17 UTC, jhlegarreta commented on _episodes/introduction.md
> +(extension <code>.bval</code>) is the diffusion-sensitizing factor, and reflects the
The bracket statement is misleading; we talk about the meaning of the parameters, but the brackets mean the files. So this needs to be reworded.

2023-04-12 00:17 UTC, jhlegarreta commented on _episodes/introduction.md
> +will be more sensitive to the diffusion of water. The b-vector (extension <code>.bvec</code>)
Same as above concerning the statement in brackets.

2023-04-12 00:17 UTC, jhlegarreta commented on _episodes/introduction.md
> +corresponds to the direction with which diffusion was measured. Together these two
Together, (?)

2023-04-12 00:17 UTC, jhlegarreta commented on _episodes/introduction.md
> +measurements (or equivalently return everything that is not a b = 0 s/mm^2)!
or equivalently,

2023-04-12 00:17 UTC, jhlegarreta commented on _episodes/introduction.md
> +are as we need them for registration in our preprocessing, (our next notebook).
preprocessing, : remove comma

2023-04-12 00:17 UTC, jhlegarreta commented on _episodes/introduction.md
> +4. Thus for every DWI volume we have an associated b-value and b-vector which tells us how we measured the diffusion.
Using all 1.'s is often times easier (items are numbered automatically).

2023-04-12 00:17 UTC, jhlegarreta commented on _episodes/introduction.md
> +the microscopic properties. The DWI acquisiton process is thus:
The DWI acquisiton process is thus: -> The DWI acquisition (note the typo to the left) process can thus be summarized in the following steps:

2023-04-12 00:17 UTC, jhlegarreta commented on _episodes/introduction.md
> +4. Thus for every DWI volume we have an associated b-value and b-vector which tells us how we measured the diffusion.
Thus for every DWI volume -> Thus, for every DWI volume, (?)

2023-05-27 13:59 UTC, jhlegarreta commented
@Bradley-Karat would you have time to address the comments or do you prefer to hand it over to somebody else? Thanks.

2023-07-11 00:00 UTC, jhlegarreta commented
@Bradley-Karat would you have time to address the comments or do you prefer to hand it over to somebody else? Thanks.

2023-07-12 19:24 UTC, Bradley-Karat commented
> @Bradley-Karat would you have time to address the comments or do you prefer to hand it over to somebody else? Thanks.

Sorry Jon just saw this now. I can go through and address some of these comments.

2023-08-12 16:52 UTC, jhlegarreta reviewed
Thanks for the effort Bradley. A few notes:
- Can you please add a commit prefix: e.g. `DOC` to signal that this his a documentation commit? Please see the commit history for guidance on this.
- We have tried to limit the line length to 79 characters so that reading the raw files is easier and for the sake of consistency. Applies to both the Markdown and Jupyter Notebooks. Although the Markdown and Jupyter Notebook rendering does not get affected by the line length, keeping a moderate and consistent number helps a lot when reviewing.

2023-08-12 16:52 UTC, jhlegarreta commented on _episodes/introduction.md
> +![Diffusion along X, Y, and Z directions. The signal in the left/right oriented corpus callosum
The text in the square brackets is the alt text. Usually a concise description of the figure. I'd prefer it stayed concise (e.g. as it was before). The caption is where the developed explanation comes.

2023-08-12 16:52 UTC, jhlegarreta commented on _episodes/introduction.md
> +4. Thus, for every DWI volume we have an associated b-value and b-vector which tells us how we measured the
Using all 1s is easier: markdown takes care of appropriately numbering the list.

2023-08-12 16:52 UTC, jhlegarreta commented on _episodes/introduction.md
> +weighted measurements (b = 0 s/mm^2, commonly referred to as the B0 volume or
Please keep the math notation here; it may need to be fixed: see the current `HEAD` rendering:
https://carpentries-incubator.github.io/SDC-BIDS-dMRI/introduction/index.html#defining-a-measurement-gradienttable

See PR #160. Our fault, sorry. This should be a separate commit.

Applies to the preprocessing episode as well, e.g.
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/blob/cc06f9a0d0d95099000c7cbb49914f552fd4d77c/_episodes/preprocessing.md?plain=1#L31

Let me know if you prefer me to do this. It will require a rebase and fixing conflicts in any case.

2023-08-12 16:52 UTC, jhlegarreta commented on _episodes/introduction.md
> +measurements (or equivalently, return everything that is not a b = 0 s/mm^2)!
Math notation.

2023-08-12 16:52 UTC, jhlegarreta commented on _episodes/preprocessing.md
> +7 b = 0 s/mm^2 volumes (non-diffusion weighted) and 60 b = 1000 s/mm^2 volumes.
Math notation.

2023-08-12 16:52 UTC, jhlegarreta commented on _episodes/preprocessing.md
> +diffusion weighting of b = 0 s/mm^2. Alternatively, if these are not
Please keep the math notation.

2023-08-12 16:52 UTC, jhlegarreta commented on _episodes/preprocessing.md
> +registering with good b = 0 s/mm^2 images.
Please keep the math notation.

2023-08-12 16:52 UTC, jhlegarreta commented on _episodes/preprocessing.md
> +b = 0 s/mm^2 volume to get the appropriate transforms to align the two
Please keep the math notation.

2023-08-12 17:00 UTC, jhlegarreta commented on _episodes/introduction.md
> +Diffusion along X, Y, and Z directions. The signal in the left-right oriented corpus callosum
Done in cc06f9a.

2023-08-12 17:00 UTC, jhlegarreta commented on _episodes/introduction.md
> +is lowest when measured along X, while the signal in the inferior-superior oriented corticospinal
Done in cc06f9a.

2023-08-12 17:01 UTC, jhlegarreta commented on _episodes/introduction.md
> +timing & strength of the diffusion gradients. A larger b-value means our DWI signal
Done in cc06f9a.

2023-08-12 17:02 UTC, jhlegarreta commented on _episodes/introduction.md
> +(extension <code>.bval</code>) is the diffusion-sensitizing factor, and reflects the
Done in cc06f9a. It reads better now. Thanks Brad.

2023-08-12 17:02 UTC, jhlegarreta commented on _episodes/introduction.md
> +will be more sensitive to the diffusion of water. The b-vector (extension <code>.bvec</code>)
Done in cc06f9a. It reads better now. Thanks Brad.

2023-08-12 17:02 UTC, jhlegarreta commented on _episodes/introduction.md
> +corresponds to the direction with which diffusion was measured. Together these two
Done in cc06f9a.

2023-08-12 17:03 UTC, jhlegarreta commented on _episodes/introduction.md
> +measurements (or equivalently return everything that is not a b = 0 s/mm^2)!
Addressed in cc06f9a.

2023-08-12 17:04 UTC, jhlegarreta commented on _episodes/introduction.md
> +are as we need them for registration in our preprocessing, (our next notebook).
Addressed in cc06f9a.

2023-08-12 17:06 UTC, jhlegarreta commented on _episodes/introduction.md
> +4. Thus for every DWI volume we have an associated b-value and b-vector which tells us how we measured the diffusion.
Same comment done in https://github.com/carpentries-incubator/SDC-BIDS-dMRI/pull/222#discussion_r1292360884

2023-08-12 17:06 UTC, jhlegarreta commented on _episodes/introduction.md
> +the microscopic properties. The DWI acquisiton process is thus:
Addressed in cc06f9a.

2023-08-12 17:07 UTC, jhlegarreta commented on _episodes/introduction.md
> +4. Thus for every DWI volume we have an associated b-value and b-vector which tells us how we measured the diffusion.
Addressed in cc06f9a.

2023-08-12 17:07 UTC, jhlegarreta commented on _episodes/introduction.md
> +diffusion-weighted images (DWI). Water diffusion that is occuring along the same
Addressed in cc06f9a.

2023-08-12 17:09 UTC, jhlegarreta commented
Also, change the commit subject and message: the preprocessing episode was also changed.

2023-08-13 19:54 UTC, jhlegarreta commented on _episodes/introduction.md
> +weighted measurements (b = 0 s/mm^2, commonly referred to as the B0 volume or
Went ahead and opened PR #238 to allow rendering LaTeX math syntax in the introduction and preprocessing episodes. Once merged, rebasing this PR on `main` would be ideal.

2023-09-09 21:52 UTC, jhlegarreta commented
@Bradley-Karat can you please address the comments made?

2023-09-16 21:16 UTC, jhlegarreta commented on _episodes/introduction.md
> +4. Thus for every DWI volume we have an associated b-value and b-vector which tells us how we measured the diffusion.
Done in db4baa2.

2023-09-16 21:20 UTC, jhlegarreta commented on code/introduction.ipynb
> +    "1. Thus, for every DWI volume we have an associated b-value and b-vector which \n",
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/pull/222#discussion_r1163441244 only applied to Markdown.

2023-09-16 21:20 UTC, jhlegarreta commented on _episodes/introduction.md
> +weighted measurements (b = 0 s/mm^2, commonly referred to as the B0 volume or
Done in db4baa2.

2023-09-16 21:24 UTC, jhlegarreta requested changes
Please, add a commit prefix (i.e. `DOC:`) and message body to the commit explaining the changes. [This](https://cbea.ms/git-commit/) is an excellent post on why this matters.

2023-11-02 12:59 UTC, jhlegarreta commented
@Bradley-Karat Can the comments above be addressed, please?

2023-11-09 02:42 UTC, jhlegarreta commented
Pinging @Bradley-Karat.

2023-11-12 19:13 UTC, jhlegarreta commented on _episodes/introduction.md
> +4. Thus, for every DWI volume we have an associated b-value and b-vector which tells us how we measured the
Done in b2e30d0.

2023-11-12 19:14 UTC, jhlegarreta commented on _episodes/introduction.md
> +measurements (or equivalently, return everything that is not a b = 0 s/mm^2)!
Done in b2e30d0.

2023-11-12 19:15 UTC, jhlegarreta commented on _episodes/preprocessing.md
> +7 b = 0 s/mm^2 volumes (non-diffusion weighted) and 60 b = 1000 s/mm^2 volumes.
Done in b2e30d0.

2023-11-12 19:15 UTC, jhlegarreta commented on _episodes/preprocessing.md
> +diffusion weighting of b = 0 s/mm^2. Alternatively, if these are not
Reverted in b2e30d0.

2023-11-12 19:15 UTC, jhlegarreta commented on _episodes/preprocessing.md
> +registering with good b = 0 s/mm^2 images.
Reverted in b2e30d0.

2023-11-12 19:15 UTC, jhlegarreta commented on _episodes/preprocessing.md
> +b = 0 s/mm^2 volume to get the appropriate transforms to align the two
Reverted in b2e30d0.

2023-11-12 19:16 UTC, jhlegarreta commented on code/introduction.ipynb
> +    "1. Thus, for every DWI volume we have an associated b-value and b-vector which \n",
Changed in b2e30d0.

2023-11-12 22:05 UTC, jhlegarreta commented
Thanks for addressing the comments @Bradley-Karat.

Usual tests timing out. Merging.

2023-11-12 22:16 UTC, merged

2023-11-12 23:28 UTC, jhlegarreta commented on _episodes/introduction.md
> +![Diffusion along X, Y, and Z directions. The signal in the left/right oriented corpus callosum
PR #244. Does not look like captions are rendered different from regular text, but anyways, done.