ENH: Add additional local reconstruction model lesson
carpentries-incubator/SDC-BIDS-dMRI pull request #27
Opened 2020-11-03 02:45 UTC by jhlegarreta

Add additional local reconstruction model lesson: add Constrained Spherical
Deconvolution (CSD) lesson.

2020-11-03 14:16 UTC, kaitj requested changes
Overall, looks good - made a couple of suggestions in the markdown file, which will probably have to be changed in the notebook as well. 

I also noted that the figures look like they were pointing to `../fig/1`, but it looks like the screenshots were saved in `../fig/5`? I'm just looking at this through git, so I'm not sure if they actually load.

2020-11-03 14:16 UTC, kaitj commented on _episodes/05-constrained-spherical-deconvolution.md
> +where $R$ is the number of coefficients. For example, an order $l_{max} = {4, 5, 6}$ SH
I believe in the example, you meant to have `$l_{max} = {4,6,8}$`. May be good to to briefly mention why the maximum order is always even (I think they talk about it in the Tournier paper).

2020-11-03 14:16 UTC, kaitj commented on _episodes/05-constrained-spherical-deconvolution.md
> +The tensor generated belonging to the response function must be prolate (two
May need to explain why this is the case as it may not be clear / obvious to someone who might be trying to completely new to diffusion

2020-11-03 23:43 UTC, jhlegarreta commented on _episodes/05-constrained-spherical-deconvolution.md
> +where $R$ is the number of coefficients. For example, an order $l_{max} = {4, 5, 6}$ SH
Nice catch :+1: . Thanks. Fixed in 94b3f0e, and also added the corresponding explanation on the use of even orders.

2020-11-03 23:44 UTC, jhlegarreta commented on _episodes/05-constrained-spherical-deconvolution.md
> +The tensor generated belonging to the response function must be prolate (two
Done in 94b3f0e.

2020-11-03 23:44 UTC, jhlegarreta commented
> I also noted that the figures look like they were pointing to ../fig/1, but it looks like the screenshots were saved in ../fig/5? I'm just looking at this through git, so I'm not sure if they actually load.

You are right :+1:, sorry, my bad. Fixed in 94b3f0e.

2020-11-04 15:56 UTC, josephmje commented on _episodes/05-constrained-spherical-deconvolution.md
> +- "What is Constrained Spherical Deconvolution?"
```suggestion
- "What is Constrained Spherical Deconvolution (CSD)?"
```

2020-11-04 16:07 UTC, jhlegarreta commented on _episodes/05-constrained-spherical-deconvolution.md
> +- "What is Constrained Spherical Deconvolution?"
Done in 37ff37b.

2020-11-24 21:34 UTC, kaitj approved these changes
Looks good to me now!

2020-12-10 23:57 UTC, merged