DOC: Add setup instructions
carpentries-incubator/SDC-BIDS-dMRI pull request #50
Opened 2021-01-23 15:34 UTC by jhlegarreta

Add setup instructions.

Create the `links.md` file to host the links, and hence to avoid inconsistencies when using links across multiple files.

2021-01-23 15:36 UTC, jhlegarreta commented on setup.md
> +Additionally, the `Jupyter` dependency needs to be installed as well:
Not sure why this is not in the `requirements.txt` file. @kaitj @josephmje any idea? Not sure how binder deal with these.

2021-01-23 15:38 UTC, jhlegarreta commented on _includes/links.md
> +{% include gh_variables.html %}
Not sure if these are necessary.

2021-01-23 15:42 UTC, jhlegarreta commented on setup.md
> +root: .
Not sure whether the `root` statement is necessary.

2021-01-23 15:45 UTC, jhlegarreta commented
A few concerns:
- Not sure whether `_includes` is the appropriate location for the `links.md` file. I could not find the necessary help in the Carpentries template instructions.
- Related to the above, not sure whether `{% include links.md %}` adds them regardless.
- How are the links singular/plural forms managed, e.g. we may want to link both when saying [Jupyter Notebook] or [Jupyter Notebooks]?

@tobyhodges can you maybe cast some light on the above, and [this](https://github.com/carpentries-incubator/SDC-BIDS-dMRI/pull/50#discussion_r563166530) and [this](https://github.com/carpentries-incubator/SDC-BIDS-dMRI/pull/50#discussion_r563166182) other comment, please?

2021-01-23 15:59 UTC, kaitj commented on setup.md
> +Additionally, the `Jupyter` dependency needs to be installed as well:
I think some of the requirements got removed when we paired down the list and should probably be added back in.

2021-01-23 16:00 UTC, kaitj approved these changes
Looks good to me. We should update the `requirements.txt` in a separate PR

2021-01-25 16:04 UTC, josephmje commented on _extras/guide.md
> +* Be clear about the purpose and convenience of using [Jupyter Notebook]s to
```suggestion
* Be clear about the purpose and convenience of using [Jupyter Notebook] to
```

2021-01-25 16:05 UTC, josephmje commented on setup.md
> +This lesson uses [Jupyter Notebook]s as a web-based interactive computational
```suggestion
This lesson uses [Jupyter Notebook] as a web-based interactive computational
```

2021-01-25 16:13 UTC, jhlegarreta commented on setup.md
> +This lesson uses [Jupyter Notebook]s as a web-based interactive computational
Done in c936214. Force pushed.

2021-01-25 16:13 UTC, jhlegarreta commented on _extras/guide.md
> +* Be clear about the purpose and convenience of using [Jupyter Notebook]s to
Done in c905e13. Force pushed.

2021-01-25 16:16 UTC, josephmje commented on setup.md
> +Additionally, the `Jupyter` dependency needs to be installed as well:
The Python requirements are meant to be as minimal as possible. The user can decide whether they want to use Jupyter or iPython to run the code. If using Anaconda, these things may also already be installed. On the Binder side, Jupyter is part of the environment by default.

2021-01-25 16:18 UTC, josephmje commented on setup.md
> +Additionally, the `Jupyter` dependency needs to be installed as well:
Perhaps we can copy instructions from one of the Carpentries' Python courses: https://swcarpentry.github.io/python-novice-inflammation/setup.html. This one gives a few different options for using Python.

2021-01-26 02:10 UTC, jhlegarreta commented on setup.md
> +Additionally, the `Jupyter` dependency needs to be installed as well:
Thanks for all these details @josephmje ! I re-worked the concerned part in 55ae3d7: added the `IPython` possibility, explained how to start the servers, and cross-referenced the `Programming with Python` Carpentries lesson.

And I agree then that since users may not use `Jupyter` not adding it to the `requirements.txt` file is reasonable :+1:.

2021-01-28 17:26 UTC, josephmje commented on _includes/links.md
> +{% include gh_variables.html %}
Looks like we only have `syllabus.html` in our `_includes` folder. Atm, these lines don't do anything but do you know it would be worth adding these files to our repository?

2021-01-28 17:28 UTC, josephmje commented on setup.md
> +root: .
Interesting. It looks like `root` can be used to trick the depth of the page compared to the root folder. I wonder if this can be used to our advantage for linking figures.

2021-01-28 17:29 UTC, josephmje commented on setup.md
> +Additionally, the `Jupyter` dependency needs to be installed as well:
Thanks for those updates!

2021-01-28 18:21 UTC, jhlegarreta commented on _includes/links.md
> +{% include gh_variables.html %}
Not sure Joseph; I saw them in another lesson of the Carpentries. I am not sure they'd refer to files in the `_includes` folder either. Maybe @tobyhodges can cast some light ?

Otherwise, I'd be fine removing them, merging, then seeing if it works, and adding a fix later if necessary to avoid adding unnecessary things for the current state of the repository/contents.

2021-01-28 18:23 UTC, jhlegarreta commented on setup.md
> +root: .
> I wonder if this can be used to our advantage for linking figures.

Not sure if I get this; you'd like to change the depth of the lesson Markdown files?

2021-01-28 18:29 UTC, josephmje commented on setup.md
> +root: .
I was thinking that if `root: .` is added, maybe any links we include in the page is relative to the project root folder. Not sure if that's correct.

2021-01-28 18:36 UTC, jhlegarreta commented on setup.md
> +root: .
That makes sense. Not sure if we prefer that; if we go for that, it might be more consistent to do it everywhere?

2021-01-29 10:22 UTC, tobyhodges commented on _includes/links.md
> +{% include gh_variables.html %}
`base_path.html` and `gh_variables.html` are components of the lesson template, helping make consistent internal links and initialising some important internal variables respectively. (View the source files for [`base_path.html`](https://github.com/carpentries/carpentries-theme/blob/master/_includes/base_path.html) and [`gh_variables.html`](https://github.com/carpentries/carpentries-theme/blob/master/_includes/gh_variables.html).)

By default, components like these, `_includes/syllabus.html`, and `_includes/links.md` will be loaded from the lesson template, and they should only be defined locally in your lesson repository where you wish to override the default with a customised version of the component. This is what we did when we added the local version of `_includes/syllabus.html` to define an adapted Syllabus table in #47. It is seldom necessary to define local versions of `base_path.html` and `gh_variables.html`, but you should not remove these `{% include [...]` lines from the file because loading the components here helps correctly define the link references contained in `_includes/links.md`.

Which brings us to `_includes/links.md`: it is often useful to override the [default version of this file](https://github.com/carpentries/carpentries-theme/blob/master/_includes/links.md) with a local copy, so you can add additional link references for use throughout your lesson. But you should make sure your local version contains [all the link references from the default version](https://raw.githubusercontent.com/carpentries/carpentries-theme/master/_includes/links.md) as well, because many of those references are vital to the normal function of the lesson template (e.g. internal links to the Setup, Code of Conduct, License, etc pages of your lesson).

I hope this helps clear things up - please ping me again if you would like any more information/clarification.

2021-01-29 10:36 UTC, tobyhodges commented on setup.md
> +root: .
you don't need to define the `root` and `layout` variables in the Setup page - these are set as defaults in the global configuration of your lesson ([`_config.yml`](https://github.com/carpentries-incubator/SDC-BIDS-dMRI/blob/b675bbf47010ed260d2a7775d7a8aefdc3559e2e/_config.yml#L90)). 

If you want this page to include internal links to other pages in your lesson, my advice is to add the `{% include base_path.html %}` line to the top of the page content, so that you can write internal link paths as `{{ relative_root_path }}/page_name/`. This is a bit clunky, but it has the advantage that links will work in locally-built versions of the lesson site as well as the online version.

2021-01-30 02:14 UTC, jhlegarreta commented on _includes/links.md
> +{% include gh_variables.html %}
Your explanation is fully enlightening @tobyhodges ! :100:  Thanks for having taken the time for this.

I'll  bring the link references from the default version to the file then 👌 !

2021-01-30 02:19 UTC, jhlegarreta commented on setup.md
> +root: .
Interesting ! Thanks again for having taken the time to walk us through these !

Will remove them, and will add follow the advice in the future if we require internal link paths.

2021-01-30 02:34 UTC, jhlegarreta commented on _includes/links.md
> +{% include gh_variables.html %}
Done in 7fc75df.

2021-01-30 02:34 UTC, jhlegarreta commented on setup.md
> +root: .
Done in 7fc75df.

2021-01-30 02:40 UTC, jhlegarreta commented on _includes/links.md
> +{% include gh_variables.html %}
@tobyhodges I assume comment lines are allowed in the `links.md` file, right?

2021-01-30 02:41 UTC, jhlegarreta commented
@josephmje  The netlify checks are awesome !! The builds are failing because at least one of our dependencies requires Python 3, and the netlify deployment is using Python 2.7.

2021-02-01 10:31 UTC, tobyhodges commented on _includes/links.md
> +{% include gh_variables.html %}
`links.md` will be inserted into the page as normal Markdown, so you can use any valid Markdown or HTML syntax in there, including `<!-- HTML comments -->` and `{% comment %} Liquid comments {% endcomment %}`

2021-02-01 10:37 UTC, tobyhodges commented
> How are the links singular/plural forms managed, e.g. we may want to link both when saying [Jupyter Notebook] or [Jupyter Notebooks]?

You need to add a link every time you want to link text but, by using reference-style links i.e. 

```markdown
[link text][link-target]

[link-target]: https://carpentries.org
```

and saving your link references into `_includes/links.md`, you can save yourself the trouble of having to define each link target more than once. Remember to `{% include links.md %}` at the end of each episode file. 

> Not sure whether _includes is the appropriate location for the links.md file. I could not find the necessary help in the Carpentries template instructions.
> Related to the above, not sure whether {% include links.md %} adds them regardless.

I think I addressed these two questions elsewhere already? 

If you would like to learn more about `{% include [...] %}` and what it is doing, you might find [this Episode of the Jekyll lesson I've been working on](https://carpentries-incubator.github.io/jekyll-pages-novice/includes/index.html) helpful.

2021-02-02 01:09 UTC, jhlegarreta commented on _includes/links.md
> +{% include gh_variables.html %}
Thanks for the explanation @tobyhodges 💯 !

2021-02-02 01:29 UTC, jhlegarreta commented
> You need to add a link every time you want to link text but, by using reference-style links i.e.
[link text][link-target]
[link-target]: https://carpentries.org
and saving your link references into _includes/links.md, you can save yourself the trouble of having to define each link target more than once. Remember to {% include links.md %} at the end of each episode file.

For the sake of correctedness, should this `[link text][link-target]` be `[link text](link-target)` ?

But otherwise :+1:, crystal clear.

> I think I addressed these two questions elsewhere already?

Yes, I think I asked twice: once in a general comment, and another time inline. Sorry :pray: !

> If you would like to learn more about {% include [...] %} and what it is doing, you might find this Episode of the Jekyll lesson I've been working on helpful.

I had a look at the lesson contents, simply awesome. Thanks for all this work and support @tobyhodges !

2021-02-02 08:24 UTC, tobyhodges commented
> should this `[link text][link-target]` be `[link text](link-target)`?

The two syntax options for links in Markdown are

1. inline-style, where the link URL is wrapped in `()`:

```markdown
[Dinosaur Comics](https://qwantz.com)
```

2. reference-style, where the link reference and the link text are both wrapped in `[]`:

```markdown
[Dinosaur Comics][qwantz]


[qwantz][https://qwantz.com]
```

I recommend the second option because it saves re-typing the link every time, and it makes re-factoring much easier if/when you need to update the URL for a link that appears multiple times throughout your site (especially when combined with `{%include links.md %}`.

2021-02-02 13:46 UTC, jhlegarreta commented
> reference-style, where the link reference and the link text are both wrapped in `[]`:

I did not know that we could use a link text with this syntax ! :ok_hand: Thanks :100: !!

2021-02-02 13:47 UTC, jhlegarreta commented
@kaitj @josephmje Ready to be reviewed and merged.

2021-02-02 14:07 UTC, kaitj approved these changes
Still looks good to me - good to know about the links!

2021-02-02 14:12 UTC, josephmje requested changes
I just included some minor edits for typos/clarity. Thanks for adding this @jhlegarreta! Fine with me to merge once those changes are in.

2021-02-02 14:12 UTC, josephmje commented on setup.md
> +[Binder] enables to open the collection of notebooks in this lesson in a
```suggestion
[Binder] enables the user to open the collection of notebooks in this lesson in a
```

2021-02-02 14:12 UTC, josephmje commented on setup.md
> +web-based executable and interactive environment. No software part needs to be
```suggestion
web-based executable and interactive environment. No additional software needs to be
```

2021-02-02 14:12 UTC, josephmje commented on setup.md
> +If users chose to run the `Jupyter Notebooks` locally, the following primary
```suggestion
If users chose to run the `Jupyter Notebooks` locally, the following
```

2021-02-02 14:12 UTC, josephmje commented on setup.md
> +> different projects separate by creating isolated, self-contained directory
```suggestion
> different projects separate by creating an isolated, self-contained directory
```

2021-02-02 14:12 UTC, josephmje commented on setup.md
> +> particular version of `Python`, and a project. This allows to have different
```suggestion
> particular version of `Python`, and a project. This allows one to have different
```

2021-02-02 14:12 UTC, josephmje commented on setup.md
> +> environment is used or not). This setup instructions will use [pip].
```suggestion
> environment is used or not). These setup instructions will use [pip].
```

2021-02-02 14:12 UTC, josephmje commented on setup.md
> +The rest of the primary dependencies (`DIPY`, `FURY`, `Matplotlib`, `Nilearn`,
```suggestion
The rest of the dependencies (`DIPY`, `FURY`, `Matplotlib`, `Nilearn`,
```

2021-02-02 14:12 UTC, josephmje commented on setup.md
> +`Jupyter` dependency can be installed running:
```suggestion
`Jupyter` dependency can be installed by running:
```

2021-02-03 00:07 UTC, jhlegarreta commented on setup.md
> +without installing any part locally. However, users may chose to run the
Thanks for the review. Done in 0c11f3c. Force pushed.

2021-02-03 00:07 UTC, jhlegarreta commented on setup.md
> +few additional non-`Python` tools required.
Thanks for the review. Done in 0c11f3c. Force pushed.

2021-02-03 00:07 UTC, jhlegarreta commented on setup.md
> +> `Notebooks`; if users chose to run the notebooks locally, they will require
Thanks for the review. Done in 0c11f3c. Force pushed.

2021-02-03 00:07 UTC, jhlegarreta commented on setup.md
> +[Binder] enables to open the collection of notebooks in this lesson in a
Thanks for the review. Done in 0c11f3c. Force pushed.

2021-02-03 00:07 UTC, jhlegarreta commented on setup.md
> +web-based executable and interactive environment. No software part needs to be
Thanks for the review. Done in 0c11f3c. Force pushed.

2021-02-03 00:07 UTC, jhlegarreta commented on setup.md
> +If users chose to run the `Jupyter Notebooks` locally, the following primary
Thanks for the review. Done in 0c11f3c. Force pushed.

2021-02-03 00:08 UTC, jhlegarreta commented on setup.md
> +> different projects separate by creating isolated, self-contained directory
Thanks for the review. Done in 0c11f3c. Force pushed.

2021-02-03 00:08 UTC, jhlegarreta commented on setup.md
> +> particular version of `Python`, and a project. This allows to have different
Thanks for the review. Done in 0c11f3c. Force pushed.

2021-02-03 00:08 UTC, jhlegarreta commented on setup.md
> +> environment is used or not). This setup instructions will use [pip].
Thanks for the review. Done in 0c11f3c. Force pushed.

2021-02-03 00:08 UTC, jhlegarreta commented on setup.md
> +The rest of the primary dependencies (`DIPY`, `FURY`, `Matplotlib`, `Nilearn`,
Thanks for the review. Done in 0c11f3c. Force pushed.

2021-02-03 00:08 UTC, jhlegarreta commented on setup.md
> +`Jupyter` dependency can be installed running:
Thanks for the review. Done in 0c11f3c. Force pushed.

2021-02-03 15:50 UTC, josephmje commented on setup.md
> +If users chose to run the `Jupyter Notebooks` locally, the following
```suggestion
If users choose to run the `Jupyter Notebooks` locally, the following
```

2021-02-03 15:50 UTC, josephmje commented on setup.md
> +pre-installed. However, users may chose to run the notebooks locally. In that
```suggestion
pre-installed. However, users may choose to run the notebooks locally. In that
```

2021-02-03 16:26 UTC, josephmje approved these changes

2021-02-03 16:27 UTC, merged

2021-02-03 16:55 UTC, jhlegarreta commented on setup.md
> +If users chose to run the `Jupyter Notebooks` locally, the following
Done in 5538f27. Force pushed.

2021-02-03 16:55 UTC, jhlegarreta commented on setup.md
> +pre-installed. However, users may chose to run the notebooks locally. In that
Done in 5538f27. Force pushed.