ENH: Refactor tractography episodes
carpentries-incubator/SDC-BIDS-dMRI pull request #59
Opened 2021-02-08 22:12 UTC by jhlegarreta

Refactor tractography episodes:
- Add the deterministic tracking episode Markdown file.
- Make the deterministic tractography be consistent with the dataset and subject
  id used in the current version of the lesson.
- Use `matplotlib` to display the tractogram scene in the deterministic
  tractography episode and avoid opening the `fury` window.
- Add contents to the local tracking Markdown file.
- Improve the explanations in the probabilistic tracking episode.
- Refactor the tractography general Markdown file to make the contents more
  consistent across the related episodes.
- Remove the output error messages in the deterministic tracking Jupyter
  notebook.

Take advantage of the commit to:
- Remove the `{: .language-python}` episode Markdown-specific markup from the
  probabilistic tracking Jupyter notebook.
- Remove the episode Markdown-specific header from the probabilistic tracking
  Jupyter notebook.
- Add the subject id to the probabilistic tracking Markdown file and remove the
  unnecessary/unused call to `window.record`.
- Make the episode titles be consistent.
- Use the reference to the first work that proposed the global tracking method.
- Fix typos (e.g. `propogate` to `propagate`; `see density` to `seed density`).
- Use the term "episode" to refer to the sections.
- Use a double white space before inline comments to conform to PEP8.

Please delete this line and the text below before submitting your contribution.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.  

---

2021-02-09 14:02 UTC, kaitj requested changes
Looks good, a couple of things should be addressed and I've added comments to those lines.

Not sure if this was discussed, but maybe we should think about updating the file names to match the episode number? For example, `08-deterministic_tractography.md` corresponds to episode 4.2.

2021-02-09 14:29 UTC, jhlegarreta commented on _episodes/08-deterministic_tractography.md
> +We can then display the resulting streamlines using the `fury` python package
Re-worded in 13fdeec.

2021-02-09 14:30 UTC, jhlegarreta commented on _episodes/08-deterministic_tractography.md
> +> This step may take a while to run_
It was a leftover from the italics syntax from the notebook. Addressed in faf8ff5.

2021-02-09 14:38 UTC, jhlegarreta commented
> Not sure if this was discussed, but maybe we should think about updating the file names to match the episode number? For example, 08-deterministic_tractography.md corresponds to episode 4.2.

Yep, we have mentioned this before (e.g. [here](https://github.com/carpentries-incubator/SDC-BIDS-dMRI/pull/47#issuecomment-762560492) and [here](https://github.com/carpentries-incubator/SDC-BIDS-dMRI/pull/52#issuecomment-766915476)). Rather than updating the names to match the episode number, I'd rename the files to partially match the episode content/title. That way, when a new episode has to be added somewhere in the middle we would not need to rename all subsequent files.

Whether we do it one way or the other, I'd do it in a separate PR to push things forward.

2021-02-09 18:55 UTC, kaitj reviewed
Looks good, just one minor spelling correction in `08-deterministic_tractography.md`

2021-02-09 18:55 UTC, kaitj commented on _episodes/08-deterministic_tractography.md
> +- "Deterministric tractography methods perform tracking in a predictable way"
Spelling here - "Deterministic"

2021-02-09 19:07 UTC, jhlegarreta commented on _episodes/08-deterministic_tractography.md
> +- "Deterministric tractography methods perform tracking in a predictable way"
:+1: Fixed in 7b15bf5.

2021-02-11 14:52 UTC, josephmje commented
Thanks @jhlegarreta! I don't know as much about tractography so I'll let @kaitj provide his input here. I'm happy to take a stab at working through these lessons once they're merged to see if I can help with clarity as a "newish" learner.

Also, looks like the website previews are finally working!

2021-02-11 16:24 UTC, jhlegarreta commented
> I'm happy to take a stab at working through these lessons once they're merged to see if I can help with clarity as a "newish" learner.

Thanks Michael. Yes, a few parts will require some changes throughout the lesson, but the essential/core aspects/content is there. IMHO the lesson is getting close to being stable.

> Also, looks like the website previews are finally working!

Yes, I saw that. Wonderful, extremely useful :100: ! Thanks for doing that.

2021-02-11 18:50 UTC, kaitj reviewed
Just a couple more minor things, otherwise it looks good. 

The example output shown (line 316+ in `09-probabilistic tractography.md`) looks good in an IDE / on git (probably as this what is shown in the terminal), but is hard to read on the rendered site. I wonder if it would be helpful to put in a code block? Can be done in another PR.

2021-02-11 18:50 UTC, kaitj commented on _episodes/09-probabilistic_tractography.md
>  pathway in a step-wise fashion and propagating streamlines based on the local
would change "propagating streamlines based on the local..." to "propagate streamlines based on the local..."

2021-02-11 19:09 UTC, jhlegarreta commented on _episodes/09-probabilistic_tractography.md
>  pathway in a step-wise fashion and propagating streamlines based on the local
Changed in f6bd4c9. Force pushed.

2021-02-11 19:17 UTC, jhlegarreta commented
> The example output shown (line 316+ in 09-probabilistic tractography.md) looks good in an IDE / on git (probably as this what is shown in the terminal), but is hard to read on the rendered site. I wonder if it would be helpful to put in a code block? Can be done in another PR.

You're right, it does not look nice on the website. Needs definitely to be reworked. Best would be a separate PR.

2021-02-11 19:17 UTC, jhlegarreta commented
Ready to be merged.

2021-02-11 19:22 UTC, kaitj approved these changes
Looks good! And yeah we can do a separate PR for the code output.

2021-02-11 19:54 UTC, merged